GET http://localhost:8080/books


###

GET http://localhost:8080/book/105


###

POST http://localhost:8080/book
Content-Type: application/x-www-form-urlencoded

name=redis&author=李四&price=19.9

<> 2020-01-08T015942.200.json

###

PUT http://localhost:8080/book
Content-Type: application/x-www-form-urlencoded

bookId=117&name=redis&author=李小四&price=9.9

<> 2020-01-08T020048.200.json

###

DELETE http://localhost:8080/book/117

<> 2020-01-08T020134.200.json
<> 2020-01-08T020120.200.json

###
